SELECT TOP (1000) [id]
      ,[fecha]
      ,[hora]
      ,[mensaje]
      ,[id_clasificacion_urgencia]
      ,[id_ticket]
      ,[id_usuario]
  FROM [ticketsIPOR].[dbo].[recepcion]

  SELECT TOP (1000) [id]
      ,[descripcion]
      ,[fecha]
      ,[hora]
      ,[id_clasificacion_atencion]
      ,[id_ticket]
      ,[id_usuario]
  FROM [ticketsIPOR].[dbo].[servicio]
  SELECT TOP (1000) [id]
      ,[descripcion]
      ,[fecha]
      ,[hora]
      ,[id_clasificacion_incidencia]
      ,[id_fase_ticket]
      ,[id_usuario]
  FROM [ticketsIPOR].[dbo].[ticket]
  SELECT TOP (1000) [id]
      ,[archivo]
      ,[nombre]
      ,[tipo_contenido]
      ,[id_ticket]
  FROM [ticketsIPOR].[dbo].[archivo_adjunto]
